### ISSUE TITLE
My related project (change method signatures, add/rm decorators, etc)

### ISSUE THREAD

**Issue by vindarel** [JackCrawley/pygen#2]
Hi !

I'm just discovering your project while browsing the melpa PR, so congrats, that looks really useful, come tell on reddit as soon as this is accepted in melpa ! and I figured I should share some utils of mine: https://gitlab.com/vindarel/redbaron4emacs Our projects are complementary but do things in common, like adding a decorator (I suggest a list of decorators already used in the file, it's a bit quicker, and also if it is "classmethod" I remove an eventual "self".). My initial goal was to change method signatures, so I have functions to add, rename, remove a method argument, rename the current def, etc, while trying (not very well) to refactor inside a def or in the project when needed/asked.

Also, I wanted to have a solid foundation to manipulate python code, so I use the redbaron lib (a bit, not always, but I believe it has great potential).

Lastly, I rely a lot on an [Hydra](https://github.com/abo-abo/hydra/) to expose all my commands, I suggest you think about it. That way, I may very well add a key to call pygen: it's complementary.

Thanks for your attention !

**Comment by JackCrawley** [comment]
This is excellent! I wasn't aware of Redbaron. Pygen was mainly an attempt to hack some utilities together that I missed from Netbeans. It's been years since I migrated to Python but I like that style of coding. Rope worked, but it was too fragile for me. Redbaron looks cool, I'll check it out. 

I prefer your system for decorators. I'm going to add a toggle that will switch a method between being static and a class method when I have some time. The backend is half-written, I figured I may as well include an interactive command that plugs into it. 

Feel free to include a Hydra. It sounds like a good idea. I code by voice (long story) so I don't have much need for menus, but they would improve usability. I may add one myself, I need to move the keybindings around anyway.
